
services:
  nginx:
    build: .
    container_name: low-code-nginx
    ports:
      - "9100:9100"
    volumes:
      - ./lowCode:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    network_mode: host   # 使用 host 网络模式